import Fastify from 'fastify';
import { z } from 'zod';
import type { DB } from '../db/connection.js';

const listQuery=z.object({
  from:z.string().datetime().optional(),to:z.string().datetime().optional(),pool:z.string().max(100).optional(),
  strategy:z.string().max(60).optional(),role:z.string().max(30).optional(),tool:z.string().max(80).optional(),
  page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(25),
  sort:z.string().optional(),order:z.enum(['asc','desc']).default('desc')
});
type ListQuery = z.output<typeof listQuery>;
const eligible=`performance_quality IN ('verified_modern','legacy_performance_only')`;
const num=(v:unknown)=>typeof v==='number'?v:Number(v??0);
const money=(value:number)=>Math.round(value*1_000_000)/1_000_000;
function percentile(values:number[],p:number){if(!values.length)return null;const s=[...values].sort((a,b)=>a-b);return s[Math.max(0,Math.ceil(p*s.length)-1)]??null;}
function meta(db:DB,included?:number){const total=num((db.prepare('SELECT COUNT(*) n FROM performance_records').get() as any)?.n);const last=(db.prepare('SELECT MAX(last_seen_at) freshness FROM ingestion_sources').get() as any)?.freshness??null;return{coverage:{eligible:total-1,included:included??total-1,total},freshness:last,warnings:['PnL includes fees. Costs and post-close swap outcomes are not included.']};}
function filters(q:ListQuery,alias=''){const pre=alias?alias+'.':'';const clauses:string[]=[];const args:unknown[]=[];if(q.from){clauses.push(`${pre}recorded_at>=?`);args.push(q.from)}if(q.to){clauses.push(`${pre}recorded_at<=?`);args.push(q.to)}if(q.pool){clauses.push(`${pre}pool=?`);args.push(q.pool)}if(q.strategy){clauses.push(`${pre}strategy=?`);args.push(q.strategy)}return{sql:clauses.length?' AND '+clauses.join(' AND '):'',args};}
function parseList(value:unknown):ListQuery{const r=listQuery.safeParse(value);if(!r.success)throw Object.assign(new Error('Invalid query'),{statusCode:400,details:r.error.flatten()});return r.data;}
function csvCell(v:unknown){const s=v==null?'':String(v);return/[",\n]/.test(s)?`"${s.replaceAll('"','""')}"`:s;}

export function buildApp(db:DB){
 const app=Fastify({logger:false});
 app.setErrorHandler((error,_request,reply)=>{const err=error as Error&{statusCode?:number;details?:unknown};reply.status(err.statusCode??500).send({error:err.message,details:err.details});});
 app.get('/api/health',async()=>({ok:true,service:'meridian-analytics'}));
 app.get('/api/meta',async()=>({data:{read_only:true,schema_version:(db.prepare('SELECT MAX(version) v FROM _migrations').get() as any).v},meta:meta(db)}));
 app.get('/api/filters',async()=>({data:{pools:db.prepare(`SELECT DISTINCT pool,pool_name FROM performance_records WHERE ${eligible} ORDER BY pool_name`).all(),strategies:db.prepare(`SELECT DISTINCT strategy FROM performance_records WHERE ${eligible} ORDER BY strategy`).all().map((x:any)=>x.strategy),roles:db.prepare('SELECT DISTINCT actor FROM decisions WHERE actor IS NOT NULL ORDER BY actor').all().map((x:any)=>x.actor),tools:db.prepare('SELECT DISTINCT tool FROM action_events WHERE tool IS NOT NULL ORDER BY tool').all().map((x:any)=>x.tool)},meta:meta(db)}));
 app.get('/api/overview',async req=>{const q=parseList(req.query);const f=filters(q);const rows=db.prepare(`SELECT pnl_usd,fees_earned_usd,pnl_pct FROM performance_records WHERE ${eligible}${f.sql}`).all(...f.args) as any[];const pnl=rows.map(r=>num(r.pnl_usd)),fees=rows.reduce((a,r)=>a+num(r.fees_earned_usd),0),wins=pnl.filter(x=>x>.01),losses=pnl.filter(x=>x<-.01),neutral=pnl.length-wins.length-losses.length;const gp=wins.reduce((a,x)=>a+x,0),gl=Math.abs(losses.reduce((a,x)=>a+x,0));return{data:{realized_pnl_usd:money(pnl.reduce((a,x)=>a+x,0)),fees_earned_usd:money(fees),trade_count:rows.length,win_count:wins.length,loss_count:losses.length,breakeven_count:neutral,win_rate:rows.length?wins.length/rows.length:null,average_return_pct:rows.length?rows.reduce((a,r)=>a+num(r.pnl_pct),0)/rows.length:null,median_return_pct:percentile(rows.map(r=>num(r.pnl_pct)),.5),profit_factor:gp===0?{value:null,state:'no_wins'}:gl===0?{value:null,state:'infinite'}:{value:gp/gl,state:'finite'}},meta:meta(db,rows.length)};});
 app.get('/api/performance/series',async req=>{const q=parseList(req.query);const f=filters(q);const rows=db.prepare(`SELECT position,recorded_at,pnl_usd,fees_earned_usd,pnl_pct FROM performance_records WHERE ${eligible}${f.sql} ORDER BY recorded_at,position`).all(...f.args) as any[];let cumulative=0,peak=0;const data=rows.map(r=>{cumulative+=num(r.pnl_usd);peak=Math.max(peak,cumulative);return{...r,cumulative_pnl_usd:money(cumulative),drawdown_usd:money(cumulative-peak)}});return{data,meta:meta(db,data.length)};});
 app.get('/api/reliability/summary',async()=>{const a=db.prepare('SELECT COUNT(*) n,SUM(CASE WHEN success=1 THEN 1 ELSE 0 END) ok FROM action_events').get() as any;const failures=db.prepare(`SELECT COUNT(*) n FROM decisions WHERE type='no_deploy' AND (reason LIKE '%Max steps%' OR reason LIKE '%no tool call%')`).get() as any;return{data:{tool_actions:num(a.n),successful_tool_actions:num(a.ok),tool_success_rate:num(a.n)?num(a.ok)/num(a.n):null,recent_reliability_failures:num(failures.n)},meta:{freshness:meta(db).freshness,warnings:['Decision reliability is limited to the retained decision window.']}};});
 app.get('/api/reliability/tools',async req=>{const q=parseList(req.query);const rows=db.prepare(`SELECT tool,success,duration_ms FROM action_events WHERE tool IS NOT NULL${q.tool?' AND tool=?':''}`).all(...(q.tool?[q.tool]:[])) as any[];const groups=new Map<string,any[]>();for(const r of rows)groups.set(r.tool,[...(groups.get(r.tool)??[]),r]);const data=[...groups].map(([tool,x])=>{const d=x.map(r=>num(r.duration_ms));const ok=x.filter(r=>r.success===1).length;return{tool,count:x.length,success_count:ok,error_count:x.length-ok,success_rate:x.length?ok/x.length:null,p50_ms:percentile(d,.5),p95_ms:percentile(d,.95)}}).sort((a,b)=>b.count-a.count);return{data,meta:{freshness:meta(db).freshness}};});
 app.get('/api/strategies',async req=>{const q=parseList(req.query);const f=filters(q);const data=db.prepare(`SELECT strategy,COUNT(*) sample_size,SUM(pnl_usd) realized_pnl_usd,SUM(fees_earned_usd) fees_earned_usd,AVG(pnl_pct) average_return_pct,SUM(CASE WHEN pnl_usd>.01 THEN 1 ELSE 0 END)*1.0/COUNT(*) win_rate FROM performance_records WHERE ${eligible}${f.sql} GROUP BY strategy ORDER BY sample_size DESC`).all(...f.args);return{data,meta:meta(db)};});
 const positionSort:Record<string,string>={position:'position',pool_name:'pool_name',deployed_at:'deployed_at',closed_at:'closed_at',amount_sol:'amount_sol'};
 app.get('/api/positions',async req=>{const q=parseList(req.query);if(q.sort&&!positionSort[q.sort])throw Object.assign(new Error('Invalid sort'),{statusCode:400});const where:string[]=[];const args:unknown[]=[];if(q.pool){where.push('pool=?');args.push(q.pool)}if(q.strategy){where.push('strategy=?');args.push(q.strategy)}const total=num((db.prepare(`SELECT COUNT(*) n FROM positions${where.length?' WHERE '+where.join(' AND '):''}`).get(...args) as any).n);const order=positionSort[q.sort??'deployed_at']!;const data=db.prepare(`SELECT position,pool,pool_name,strategy,amount_sol,deployed_at,closed_at,closed,closure_quality FROM positions${where.length?' WHERE '+where.join(' AND '):''} ORDER BY ${order} ${q.order.toUpperCase()} LIMIT ? OFFSET ?`).all(...args,q.pageSize,(q.page-1)*q.pageSize);return{data,meta:{...meta(db),pagination:{page:q.page,page_size:q.pageSize,total}}};});
 app.get('/api/positions/:position',async req=>{const position=(req.params as any).position;const row=db.prepare(`SELECT p.*,pr.pnl_usd,pr.pnl_pct,pr.fees_earned_usd,pr.performance_quality,pr.close_reason,pr.recorded_at FROM positions p LEFT JOIN performance_records pr USING(position) WHERE p.position=?`).get(position);if(!row)return (app as any).httpErrors?.notFound?.()??{error:'Not found'};return{data:row,meta:meta(db)};});
 app.get('/api/decisions',async req=>{const q=parseList(req.query);const where:string[]=[];const args:unknown[]=[];if(q.role){where.push('actor=?');args.push(q.role)}if(q.from){where.push('ts>=?');args.push(q.from)}if(q.to){where.push('ts<=?');args.push(q.to)}const total=num((db.prepare(`SELECT COUNT(*) n FROM decisions${where.length?' WHERE '+where.join(' AND '):''}`).get(...args) as any).n);const data=db.prepare(`SELECT id,ts,type,actor,pool,pool_name,position,summary,reason,risks_json,metrics_json,rejected_json FROM decisions${where.length?' WHERE '+where.join(' AND '):''} ORDER BY ts DESC LIMIT ? OFFSET ?`).all(...args,q.pageSize,(q.page-1)*q.pageSize);return{data,meta:{freshness:meta(db).freshness,pagination:{page:q.page,page_size:q.pageSize,total},warnings:['Decision history is a retained rolling window.']}};});
 app.get('/api/data-quality',async()=>({data:{sources:db.prepare('SELECT name,kind,state,last_seen_at,size,generation_id,cursor_offset FROM ingestion_sources ORDER BY name').all(),performance_quality:db.prepare('SELECT performance_quality quality,COUNT(*) count FROM performance_records GROUP BY performance_quality').all(),closure_quality:db.prepare('SELECT closure_quality quality,COUNT(*) count FROM positions GROUP BY closure_quality').all(),ingestion_errors:num((db.prepare('SELECT COUNT(*) n FROM ingestion_errors').get() as any).n),signal_coverage:num((db.prepare('SELECT COUNT(*) n FROM performance_records WHERE signal_snapshot IS NOT NULL').get() as any).n)},meta:meta(db)}));
 app.get('/api/export/:dataset.csv',async(req,reply)=>{const dataset=(req.params as any).dataset;let headers:string[],rows:any[];if(dataset==='performance'){headers=['position','pool_name','strategy','recorded_at','pnl_usd','pnl_pct','fees_earned_usd','performance_quality'];rows=db.prepare(`SELECT ${headers.join(',')} FROM performance_records WHERE ${eligible} ORDER BY recorded_at`).all()}else if(dataset==='positions'){headers=['position','pool_name','strategy','deployed_at','closed_at','closure_quality'];rows=db.prepare(`SELECT ${headers.join(',')} FROM positions ORDER BY deployed_at`).all()}else throw Object.assign(new Error('Invalid export dataset'),{statusCode:400});reply.type('text/csv; charset=utf-8').header('Content-Disposition',`attachment; filename="${dataset}.csv"`);return [headers.join(','),...rows.map(r=>headers.map(h=>csvCell(r[h])).join(','))].join('\n')+'\n';});
 return app;
}
